# Automatically generated by pb2py
# fmt: off
import protobuf as p

from .CardanoAssetValuePair import CardanoAssetValuePair

if __debug__:
    try:
        from typing import Dict, List  # noqa: F401
        from typing_extensions import Literal  # noqa: F401
    except ImportError:
        pass


class CardanoMultiassetType(p.MessageType):

    def __init__(
        self,
        *,
        policy_id: bytes,
        assets: List[CardanoAssetValuePair] = None,
    ) -> None:
        self.assets = assets if assets is not None else []
        self.policy_id = policy_id

    @classmethod
    def get_fields(cls) -> Dict:
        return {
            1: ('policy_id', p.BytesType, p.FLAG_REQUIRED),
            2: ('assets', CardanoAssetValuePair, p.FLAG_REPEATED),
        }
