# Automatically generated by pb2py
# fmt: off
# isort:skip_file
import protobuf as p

from .CardanoScript import CardanoScript

if __debug__:
    try:
        from typing import Dict, List, Optional  # noqa: F401
        from typing_extensions import Literal  # noqa: F401
    except ImportError:
        pass


class CardanoGetScriptHash(p.MessageType):
    MESSAGE_WIRE_TYPE = 313

    def __init__(
        self,
        *,
        script: CardanoScript,
        show_display: bool = False,
    ) -> None:
        self.script = script
        self.show_display = show_display

    @classmethod
    def get_fields(cls) -> Dict:
        return {
            1: ('script', CardanoScript, p.FLAG_REQUIRED),
            2: ('show_display', p.BoolType, False),  # default=false
        }
