# Automatically generated by pb2py
# fmt: off
import protobuf as p

from .CardanoTokenAmountType import CardanoTokenAmountType

if __debug__:
    try:
        from typing import Dict, List  # noqa: F401
        from typing_extensions import Literal  # noqa: F401
    except ImportError:
        pass


class CardanoTokenGroupType(p.MessageType):

    def __init__(
        self,
        *,
        policy_id: bytes,
        token_amounts: List[CardanoTokenAmountType] = None,
    ) -> None:
        self.token_amounts = token_amounts if token_amounts is not None else []
        self.policy_id = policy_id

    @classmethod
    def get_fields(cls) -> Dict:
        return {
            1: ('policy_id', p.BytesType, p.FLAG_REQUIRED),
            2: ('token_amounts', CardanoTokenAmountType, p.FLAG_REPEATED),
        }
