# Automatically generated by pb2py
# fmt: off
from .. import protobuf as p

if __debug__:
    try:
        from typing import Dict, List  # noqa: F401
        from typing_extensions import Literal  # noqa: F401
    except ImportError:
        pass


class CardanoAssetAmountPair(p.MessageType):

    def __init__(
        self,
        *,
        asset_name: str,
        amount: int,
    ) -> None:
        self.asset_name = asset_name
        self.amount = amount

    @classmethod
    def get_fields(cls) -> Dict:
        return {
            1: ('asset_name', p.UnicodeType, p.FLAG_REQUIRED),
            2: ('amount', p.UVarintType, p.FLAG_REQUIRED),
        }
