# Automatically generated by pb2py
# fmt: off
# isort:skip_file
from .. import protobuf as p

if __debug__:
    try:
        from typing import Dict, List, Optional  # noqa: F401
        from typing_extensions import Literal  # noqa: F401
    except ImportError:
        pass


class CardanoScriptHash(p.MessageType):
    MESSAGE_WIRE_TYPE = 314

    def __init__(
        self,
        *,
        script_hash: bytes,
    ) -> None:
        self.script_hash = script_hash

    @classmethod
    def get_fields(cls) -> Dict:
        return {
            1: ('script_hash', p.BytesType, p.FLAG_REQUIRED),
        }
