# Automatically generated by pb2py
# fmt: off
from .. import protobuf as p

if __debug__:
    try:
        from typing import Dict, List  # noqa: F401
        from typing_extensions import Literal  # noqa: F401
    except ImportError:
        pass


class CardanoTokenAmountType(p.MessageType):

    def __init__(
        self,
        *,
        raw_asset_name: bytes,
        amount: int,
    ) -> None:
        self.raw_asset_name = raw_asset_name
        self.amount = amount

    @classmethod
    def get_fields(cls) -> Dict:
        return {
            1: ('raw_asset_name', p.BytesType, p.FLAG_REQUIRED),
            2: ('amount', p.UVarintType, p.FLAG_REQUIRED),
        }
