# Automatically generated by pb2py
# fmt: off
# isort:skip_file
if __debug__:
    try:
        from typing_extensions import Literal  # noqa: F401
    except ImportError:
        pass

PUB_KEY: Literal[0] = 0
ALL: Literal[1] = 1
ANY: Literal[2] = 2
N_OF_K: Literal[3] = 3
INVALID_BEFORE: Literal[4] = 4
INVALID_HEREAFTER: Literal[5] = 5
